custom_logo: "nf-core-sarek_logo_light.png"
custom_logo_url: https://github.com/nf-core/sarek/
custom_logo_title: "nf-core/sarek"

title: "WGS Analysis Report"
intro_text: >
  This report includes summaries of data quality, data processing, and snapshots of results for your WGS study. This report should assist you to get a general picture of the study, to spot any irregularities in the sample or data, and to  explore the most significant results.
report_comment: Please consult our <a href="https://zymo-research.github.io/pipeline-resources/report_docs/genomics_documentation.html" target="_blank">WGS report documentation</a> on how to use this report.
report_section_order:
  "nf-core-sarek-methods-description":
    order: -1000
  software_versions:
    order: -1001
  "nf-core-sarek-summary":
    order: -1002

export_plots: true

disable_version_detection: true

# Run only these modules
run_modules:
  - custom_content
  - fastqc
  - fastp
  - picard
  - samtools
  - mosdepth
  - gatk
  - bcftools
  - vcftools
  - snpeff
  - vep

module_order:
  - mosdepth:
      name: "Mosdepth"
  - snpeff:
      name: "SNPeff"
  - bcftools:
      name: "Bcftools"
  - picard:
      name: "GATK4 MarkDuplicates"
      info: " metrics generated either by GATK4 MarkDuplicates or EstimateLibraryComplexity (with --use_gatk_spark)."
  - samtools:
      name: "Samtools Flagstat"
  - fastqc:
      name: "FastQC (raw)"
      path_filters_exclude:
        - "*_val_*.zip"
  - fastp:
      name: "FastP (Read preprocessing)"
  - gatk:
      name: "GATK4 BQSR"
  - vcftools:
      name: "Vcftools"
  - vep:
      name: "VEP"

extra_fn_clean_exts:
  - "_val"
  - "-"
  - "_R1"
  - "_R2"
  - "-"
  - ".recal"
  - ".deepvariant"
  - ".manta.diploid_sv"
  - ".md"
  - "vcf.gz"
  - "_VEP"
  - "_snpEff"
  - type: regex_keep
    pattern: "^.*.(md|recal).mosdepth.(global|region).dist"
    module: mosdepth


table_columns_visible:
  FastQC (raw):
    percent_gc: false
    median_sequence_length: false
    total_sequences: false
    percent_duplicates: false
  FastP (Read preprocessing):
    pct_duplication: false
    pct_surviving: false
    filtering_result_passed_filter_reads: false


sample_names_replace_regex: True
sample_names_replace:
  "\\.[0-9]{4}$": ".md" # should match ".0001" but only at the end of strings for module Markduplicates/EstimateLibraryComplexity
  module: picard

custom_data:
  dedup_metrics:
    id: "dedup_metrics"
    section_name: "Sentieon Dedup Metrics"
    plot_type: "table"
    pconfig:
      id: "dedup_metrics"
      namespace: "Sentieon Dedup Metrics"
    headers:
      LIBRARY:
        description: "LIBRARY"
      UNPAIRED_READS_EXAMINED:
        description: "UNPAIRED_READS_EXAMINE"
      READ_PAIRS_EXAMINED:
        description: "READ_PAIRS_EXAMINED"
      SECONDARY_OR_SUPPLEMENTARY_RDS:
        description: "SECONDARY_OR_SUPPLEMENTARY_RDS"
      UNMAPPED_READS:
        description: "UNMAPPED_READS"
      UNPAIRED_READ_DUPLICATES:
        description: "UNPAIRED_READ_DUPLICATES"
      READ_PAIR_DUPLICATES:
        description: "READ_PAIR_DUPLICATES"
      READ_PAIR_OPTICAL_DUPLICATES:
        description: "READ_PAIR_OPTICAL_DUPLICATES"
      PERCENT_DUPLICATION:
        description: "PERCENT_DUPLICATION"
      ESTIMATED_LIBRARY_SIZE:
        description: "ESTIMATED_LIBRARY_SIZE"
sp:
  snpeff:
    contents: "SnpEff_version"
    max_filesize: 5000000
  dedup_metrics:
    fn: "*.metrics.multiqc.tsv"
